### ISSUE TITLE
Exception when running on eslint on flow file

### ISSUE THREAD

**Issue by bjornua** [risedigital/eslint-config-rise#7]
Steps to reproduce:

1. Make a new CRA project
2. Follow instructions for this project
3.  Create a file with contents:
```
// @flow
type Props = {};
class Page extends Test<Props> {}
```
4. Run `eslint` on that file.

```
Cannot read property 'type' of undefined
TypeError: Cannot read property 'type' of undefined
    at isForInRef (/home/bjorn/project/rise/skincoach-hcp-react/node_modules/eslint/lib/rules/no-unused-vars.js:406:24)
    at variable.references.some.ref (/home/bjorn/project/rise/skincoach-hcp-react/node_modules/eslint/lib/rules/no-unused-vars.js:443:21)
    at Array.some (<anonymous>)
    at isUsedVariable (/home/bjorn/project/rise/skincoach-hcp-react/node_modules/eslint/lib/rules/no-unused-vars.js:442:40)
    at collectUnusedVariables (/home/bjorn/project/rise/skincoach-hcp-react/node_modules/eslint/lib/rules/no-unused-vars.js:554:26)
    at collectUnusedVariables (/home/bjorn/project/rise/skincoach-hcp-react/node_modules/eslint/lib/rules/no-unused-vars.js:561:17)
    at Program:exit (/home/bjorn/project/rise/skincoach-hcp-react/node_modules/eslint/lib/rules/no-unused-vars.js:606:36)
    at listeners.(anonymous function).forEach.listener (/home/bjorn/project/rise/skincoach-hcp-react/node_modules/eslint/lib/util/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/home/bjorn/project/rise/skincoach-hcp-react/node_modules/eslint/lib/util/safe-emitter.js:45:38)
(node:27700) [ESLINT_LEGACY_OBJECT_REST_SPREAD] DeprecationWarning: The 'parserOptions.ecmaFeatures.experimentalObjectRestSpread' option is deprecated. Use 'parserOptions.ecmaVersion' instead. (found in "standard")
```

**Comment by bjornua** [comment]
Okay, I fixed the issue with running `yarn add babel-eslint`. Something something old `babel-eslint` being used somewhere if you don't have it. It's pretty nasty.
